# Generated by Django 6.0 on 2026-01-03 19:53

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlerteStock',
            fields=[
                ('id_alerte', models.AutoField(primary_key=True, serialize=False)),
                ('date_alerte', models.DateTimeField(default=django.utils.timezone.now)),
                ('message', models.TextField()),
                ('statut', models.CharField(choices=[('ENVOYEE', 'Envoyee'), ('TRAITEE', 'Traitee')], max_length=20)),
                ('seuil_declencheur', models.IntegerField()),
                ('id_produit', models.ForeignKey(db_column='id_produit', on_delete=django.db.models.deletion.CASCADE, related_name='alertes', to='products.produit')),
            ],
            options={
                'verbose_name': 'Alerte Stock',
                'verbose_name_plural': 'Alertes Stock',
                'db_table': 'alerte_stock',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id_stock', models.AutoField(primary_key=True, serialize=False)),
                ('quantite_disponible', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('seuil_minimal', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('date_derniere_mise_a_jour', models.DateTimeField(default=django.utils.timezone.now)),
                ('id_produit', models.OneToOneField(db_column='id_produit', on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='products.produit')),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stocks',
                'db_table': 'stock',
            },
        ),
    ]
