# Generated by Django 6.0 on 2026-01-03 19:53

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id_commande', models.AutoField(primary_key=True, serialize=False)),
                ('date_commande', models.DateTimeField(default=django.utils.timezone.now)),
                ('montant_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('ACCEPTEE', 'Acceptee'), ('REFUSEE', 'Refusee')], max_length=20)),
                ('id_client', models.ForeignKey(db_column='id_client', on_delete=django.db.models.deletion.CASCADE, related_name='commandes', to='accounts.client')),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
                'db_table': 'commande',
                'ordering': ['-date_commande'],
            },
        ),
        migrations.CreateModel(
            name='LigneCommande',
            fields=[
                ('id_ligne_commande', models.AutoField(primary_key=True, serialize=False)),
                ('quantite', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('montant_ligne', models.DecimalField(decimal_places=2, max_digits=12)),
                ('id_commande', models.ForeignKey(db_column='id_commande', on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='sales.commande')),
                ('id_produit', models.ForeignKey(db_column='id_produit', on_delete=django.db.models.deletion.CASCADE, related_name='lignes_commande', to='products.produit')),
            ],
            options={
                'verbose_name': 'Ligne de commande',
                'verbose_name_plural': 'Lignes de commande',
                'db_table': 'ligne_commande',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id_reservation', models.AutoField(primary_key=True, serialize=False)),
                ('date_reservation', models.DateTimeField(default=django.utils.timezone.now)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('ACCEPTEE', 'Acceptee'), ('REFUSEE', 'Refusee')], max_length=20)),
                ('id_client', models.ForeignKey(db_column='id_client', on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='accounts.client')),
            ],
            options={
                'verbose_name': 'Reservation',
                'verbose_name_plural': 'Reservations',
                'db_table': 'reservation',
                'ordering': ['-date_reservation'],
            },
        ),
        migrations.CreateModel(
            name='LigneReservation',
            fields=[
                ('id_ligne_reservation', models.AutoField(primary_key=True, serialize=False)),
                ('quantite_reservee', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('id_produit', models.ForeignKey(db_column='id_produit', on_delete=django.db.models.deletion.CASCADE, related_name='lignes_reservation', to='products.produit')),
                ('id_reservation', models.ForeignKey(db_column='id_reservation', on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='sales.reservation')),
            ],
            options={
                'verbose_name': 'Ligne de reservation',
                'verbose_name_plural': 'Lignes de reservation',
                'db_table': 'ligne_reservation',
            },
        ),
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id_vente', models.AutoField(primary_key=True, serialize=False)),
                ('date_vente', models.DateTimeField(default=django.utils.timezone.now)),
                ('chiffre_affaires', models.DecimalField(decimal_places=2, max_digits=12)),
                ('id_commande', models.OneToOneField(db_column='id_commande', on_delete=django.db.models.deletion.CASCADE, related_name='vente', to='sales.commande')),
            ],
            options={
                'verbose_name': 'Vente',
                'verbose_name_plural': 'Ventes',
                'db_table': 'vente',
                'ordering': ['-date_vente'],
            },
        ),
    ]
